name: Push to Replicate

on:
  push:
    branches:
      - main

jobs:
  push-to-replicate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}
          cog-version: v0.20.0

      - name: Push to Replicate
        run: cog push r8.im/xaoyaozi/propainter
